### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by felixgonsug** [django-oscar/django-oscar-accounts#53] opened 2017-11-30 16:45 UTC
When trying to install with pip it gives this error:

```
% pip install django-oscar-accounts

Collecting django-oscar-accounts
  Using cached django-oscar-accounts-0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-67a2pzxk/django-oscar-accounts/setup.py", line 12, in <module>
        long_description=open('README.md').read(),
      File "/usr/home/oscar-admin/.env/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 11675: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-67a2pzxk/django-oscar-accounts/

```

Im using Python 3.6.2

**Comment by prince-tanapong** [comment] 2017-12-01 06:24
I have this problem too.

**Comment by solarissmoke** [comment] 2017-12-01 11:01
This was fixed in e12c38a73e70434a0dd3f65fdffbd8ead3808ccf . Please use the latest package from master, as it hasn't been released on PyPi yet.

**Comment by prince-tanapong** [comment] 2017-12-01 12:56
@solarissmoke  I still got this problem

root@661e03d02baa:/application# pip install git+git://github.com/django-oscar/django-oscar-accounts.git@e12c38a
Collecting git+git://github.com/django-oscar/django-oscar-accounts.git@e12c38a
  Cloning git://github.com/django-oscar/django-oscar-accounts.git (to e12c38a) to /tmp/pip-40wkgchc-build
  Could not find a tag or branch 'e12c38a', assuming commit.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-40wkgchc-build/setup.py", line 26, in <module>
        long_description=open('README.rst').read(),
      File "/appenv/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 13845: ordinal not in range(128)

**Comment by solarissmoke** [comment] 2017-12-01 12:57
Okay - will reopen this and have another look.

**Comment by prince-tanapong** [comment] 2017-12-01 13:01
@solarissmoke I think It about Readme.me, when I try pulling to my local and `pip setup.py install` and I remove that line it work.

**Comment by prince-tanapong** [comment] 2017-12-01 13:06
@solarissmoke I try to folk and comment this https://github.com/prince-tanapong/django-oscar-accounts/commit/5cf54c079bb21db8d14cbe4b194185ee190868f7 and install from this it work,

I think there are some ascii code in readme file.

**Comment by felixgonsug** [comment] 2017-12-01 19:37
I solved it installing the package like this:
`
pip install django-oscar-accounts==0.4rc1 --upgrade`

I saw it in some tutorial but i dont found it now, good luck!

**Comment by solarissmoke** [comment] 2017-12-02 02:37
I am not able to reproduce this problem. There is nothing in `README.rst` that looks problematic to me.

**Comment by prince-tanapong** [comment] 2017-12-06 08:06
@solarissmoke  I think euro sign in readme course this problem, I try installing from my folk with this commit, and it work!!

https://github.com/prince-tanapong/django-oscar-accounts/commit/1fd0888d4d2b599eaf89b3ce7ee72323e76e0eeb

this is how I install
`pip install git+https://github.com/prince-tanapong/django-oscar-accounts.git@1fd0888d4d2b599eaf89b3ce7ee72323e76e0eeb`

**Comment by prince-tanapong** [comment] 2017-12-06 21:06
@all I also know the real root cause, I think the problem is we use ubuntu base docker image and when I check locale it use POSIX, So in can not decode unicode
```
locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```
After I add this to docker file, it will solve problem and can install from this repo
```
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LC_ALL en_US.UTF-8
```

Hope this help!!!

**Comment by SalahAdDin** [comment] 2017-12-06 23:08
@prince-tanapong it should to be in the docs.

**Comment by solarissmoke** [comment] 2017-12-29 04:05
This is due to underlying issues in Python (see https://bugs.python.org/issue19846) and docker (see https://github.com/docker-library/python/issues/13 for how to correct your docker config). It isn't an issue with this app itself, so closing this and leaving these links for those that run into the same problem.

**Closed by solarissmoke** 2017-12-29 04:05 UTC
